services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL="${URL}"
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=linode
      - EMAIL="${EMAIL}"
      - ONLY_SUBDOMAINS=false
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PIP_PACKAGES=certbot-dns-linode
    volumes:
      - ./swag_data/config:/config
    ports:
      - 443:443
    restart: unless-stopped
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
