---
services:
  monica:
    image: lscr.io/linuxserver/monica:latest
    container_name: monica
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DB_HOST=monica_db
      - DB_PORT=3306
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_DATABASE=${DB_NAME}
      - APP_URL=${DOMAIN}
      - APP_ENV=local
      - APP_DISABLE_SIGNUP=true
    volumes:
      - ./monica/config:/config
    restart: unless-stopped
    networks:
      - proxy_network
      - db_network

  monica_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: monica_db
    hostname: monica_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - ./db_data/config:/config
      - ./db_data/data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - db_network

networks:
  proxy_network:
    external: true
  db_network:
    driver: bridge
