#!/bin/bash

# update
sudo apt update

# Install Required Dependencies
sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common mysql-client -y

# add repo key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# add repo
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

# update
sudo apt update

# use the Docker repo
apt-cache policy docker-ce

# install Docker
sudo apt-get install docker-ce -y

# allow docker commands without sudo
sudo usermod -aG docker ${USER}

# install docker compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# start and enable docker
sudo systemctl start docker
sudo systemctl enable docker

# add user to the docker group
sudo usermod -aG docker ubuntu
sudo su - $USER
