version: "3.4"

services:
  app:
    image: monicahq/monicahq
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      APP_KEY: base64:p+kdIDygZUsl1L+Khrp23OF2P34smX4cTZp/mxp7QuQ=
      APP_ENV: "${APP_ENV}"
      APP_TRUSTED_PROXIES: "${APP_TRUSTED_PROXIES}"
      DB_HOST: db
    volumes:
      - data:/var/www/monica/storage
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql
